name: Deploy EC2 instance

on:
   push:
     branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.11.1
        
    - name: "Install Ansible"
      uses: alex-oleshkevich/setup-ansible@v1.0.1
      with:
          version: "9.3.0"

    - name: Installing aws Boto3
      run: pip install boto3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

    - name: Create S3 Bucket
      run: |
          aws s3 mb s3://clo835-assignment2-dev-s3-bucket --region us-east-1
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          
    - name: Wait for 10 seconds for creating the S3 bucket to store terraform state
      run: sleep 10
      
    - name: Verify AWS Identity
      run: aws sts get-caller-identity

    - name: SSH Key Creation
      run: ssh-keygen -t rsa -f ~/.ssh/assignment2-dev -N "" 
      
    - name: chmod 400 on the SSH key
      run: chmod 400 ~/.ssh/assignment2-dev
      
    - name: Initialize Terraform
      working-directory: EC2/deployment
      run: terraform init

    - name: Plan Terraform
      working-directory: EC2/deployment
      run: terraform plan

    - name: Apply Terraform
      working-directory: EC2/deployment
      run: terraform apply -auto-approve

    - name: Wait for 60 seconds for creating the EC2 instance
      run: sleep 60

    - name: Install dependencies
      working-directory: EC2/installation
      run: ansible-playbook -i aws_ec2.yaml playbook.yaml --private-key ~/.ssh/assignment2-dev

