apiVersion: v1
kind: Deployment
metadata:
  name: mysql
  namespace: clo835-assignment2-app
  labels:
    app: mysql-db
    tier: backend
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 103848042406.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-db:v0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "passw.rd"
            - name: MYSQL_DATABASE
              value: "employees"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "pw"
      imagePullSecrets:
        - name: ecr-secret



---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: clo835-assignment2-app
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
