apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-replicaset
  labels:
    app: employees
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: employees-web-app
          image: 103848042406.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-app:v0.1
          ports:
            - containerPort: 8080
          env:
            - name: APP_COLOR
              value: "blue"
            - name: DBHOST
              value: "mysql-service"  # Use the stable DB service
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "pw"
      imagePullSecrets:
        - name: ecr-secret
