apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-web-rs
  namespace: clo835-assignment2-app
  labels:
    app: frontend
spec:
  replicas: 3  # Ensures 3 running replicas
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 103848042406.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-app:v0.1
          ports:
            - containerPort: 8080
          env:
            - name: APP_COLOR
              value: "blue"
            - name: DBHOST
              value: "mysql-db-service"  # Use the stable DB service
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "pw"
      imagePullSecrets:
        - name: ecr-secret
